#define T_EOF 0
#define T_TYPEDEF 1
#define T_CHAR 2
#define T_INT 3
#define T_FLOAT 4
#define T_STRING 5
#define T_CONST 6
#define T_CLASS 7
#define T_PRIVATE 8
#define T_PROTECTED 9
#define T_PUBLIC 10
#define T_VOID 11
#define T_STATIC 12
#define T_UNION 13
#define T_ENUM 14
#define T_LIST 15
#define T_CONTINUE 16
#define T_BREAK 17
#define T_IF 18
#define T_ELSE 19
#define T_WHILE 20
#define T_FOR 21
#define T_RETURN 22
#define T_LENGTH 23
#define T_CIN 24
#define T_COUT 25
#define T_MAIN 26
#define T_THIS 27
#define T_ID 28
#define T_NUM 29
#define T_ICONST 30
#define T_UNKNOWN 31
#define T_FCONST 32
#define T_SCONST 33
#define T_CCONST 34
#define T_OROP 35
#define T_ANDOP 36
#define T_EQUOP 37
#define T_RELOP 38
#define T_ADDOP 39
#define T_MULOP 40
#define T_NOTOP 41
#define T_INCDEC 42
#define T_SIZEOP 43
#define T_LISTFUNC 44
#define T_LPAREN 45
#define T_RPAREN 46 
#define T_SEMI 47       
#define T_DOT 48
#define T_COMMA 49      
#define T_ASSIGN 50
#define T_COLON 51
#define T_LBRACK 52
#define T_RBRACK 53
#define T_REFER 54
#define T_LBRACE 55
#define T_RBRACE 56
#define T_METH 57
#define T_INP 58
#define T_OUT 59
#define T_ERROR -1